{
 "title": "Grafana Docker Swarm Cluster v1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(swarm_nodes_status,swarm_cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(swarm_containers_running_total,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Swarm Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Status",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "swarm_nodes_status{swarm_cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Information on cluster=$cluster",
     "type": "stat",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "swarm_stacks_total{swarm_cluster=\"$cluster\"}",
       "legendFormat": "Stack Total"
      },
      {
       "expr": "swarm_configs_total{swarm_cluster=\"$cluster\"}",
       "legendFormat": "Config Total"
      },
      {
       "expr": "swarm_secrets_total{swarm_cluster=\"$cluster\"}",
       "legendFormat": "Secret Total"
      },
      {
       "expr": "swarm_services_total{swarm_cluster=\"$cluster\"}",
       "legendFormat": "Service Total"
      },
      {
       "expr": "swarm_services_unstable_total{swarm_cluster=\"$cluster\"}",
       "legendFormat": "Unstable Total"
      },
      {
       "expr": "sum(swarm_containers_running_total{swarm_cluster=\"$cluster\"})",
       "legendFormat": "Running Containers"
      }
     ]
    },
    {
     "title": "Services Status cluster=$cluster",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(swarm_services_status{swarm_cluster=\"$cluster\"} == 0)",
       "legendFormat": "Stable"
      },
      {
       "expr": "count(swarm_services_status{swarm_cluster=\"$cluster\"} == 1)",
       "legendFormat": "Stopped"
      },
      {
       "expr": "count(swarm_services_status{swarm_cluster=\"$cluster\"} == 2)",
       "legendFormat": "Unstable"
      },
      {
       "expr": "count(swarm_services_status{swarm_cluster=\"$cluster\"} == 3)",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "Last ALL EXITED containers",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "swarm_containers_status{swarm_cluster=\"$cluster\", state=\"exited\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers Running on node=$node",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "swarm_containers_status{swarm_cluster=\"$cluster\",node=\"$node\",state=\"running\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ALL Services LAST Status on cluster=$cluster",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "swarm_services_status{swarm_cluster=\"$cluster\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}